import "server-only";
import Papa from "papaparse";
import * as XLSX from "xlsx";

// Shared CSV/JSON/Excel generation for report exports (§31). The SLASH API
// has no export endpoint of its own — every report here is generated by
// this app from data it already fetched, never claimed as coming from the
// provider.
export type ExportFormat = "csv" | "json" | "xlsx";

export function buildExportResponse(
  rows: Record<string, unknown>[],
  format: ExportFormat,
  filenameBase: string
): { body: string | Buffer; contentType: string; filename: string } {
  const filename = `${filenameBase}-${Date.now()}.${format}`;

  if (format === "json") {
    return { body: JSON.stringify(rows, null, 2), contentType: "application/json", filename };
  }

  if (format === "xlsx") {
    const worksheet = XLSX.utils.json_to_sheet(rows);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
    const buffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
    return {
      body: buffer,
      contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      filename,
    };
  }

  return { body: Papa.unparse(rows), contentType: "text/csv; charset=utf-8", filename };
}
