"use client";

import { Download, Package, Activity, MapPin, AlertTriangle, Gauge } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";

type ReportDef = {
  type: string;
  icon: typeof Package;
  title: string;
  description: string;
};

const REPORTS: ReportDef[] = [
  { type: "inventory", icon: Package, title: "Terminal Inventory", description: "Serial numbers, hardware, model, customer, and plan for every terminal." },
  { type: "status", icon: Activity, title: "Current Terminal Status", description: "Status, online/offline, signal quality, last seen, and open faults." },
  { type: "gps", icon: MapPin, title: "GPS History", description: "All recorded location points per terminal, with timestamps." },
  { type: "alerts", icon: AlertTriangle, title: "Fault / Alert History", description: "Alert episodes from the SLASH API, active and resolved." },
  { type: "usage", icon: Gauge, title: "Usage Report", description: "Data usage, priority/standard split, and allowance per terminal." },
];

const FORMATS: { format: string; label: string }[] = [
  { format: "csv", label: "CSV" },
  { format: "json", label: "JSON" },
  { format: "xlsx", label: "Excel" },
];

export function ReportsPageClient() {
  return (
    <div className="space-y-6">
      <div>
        <p className="text-2xl font-bold">Reports</p>
        <p className="text-sm text-text-muted">
          Generated by this app from already-fetched terminal data — the SLASH API has no export endpoint of its own.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {REPORTS.map((r) => (
          <Card key={r.type}>
            <CardContent className="pt-5">
              <div className="flex items-start gap-3">
                <span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-accent-blue/15 text-accent-blue">
                  <r.icon className="size-5" />
                </span>
                <div className="flex-1">
                  <p className="text-sm font-semibold text-text-primary">{r.title}</p>
                  <p className="mt-0.5 text-xs text-text-muted">{r.description}</p>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {FORMATS.map((f) => (
                      <a key={f.format} href={`/api/admin/reports/export?type=${r.type}&format=${f.format}`}>
                        <button className="flex items-center gap-1.5 rounded-xl border border-line px-3 py-1.5 text-xs font-medium text-text-secondary hover:bg-surface-raised">
                          <Download className="size-3.5" /> {f.label}
                        </button>
                      </a>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
